services:
  frontend:
    image: node:18-alpine
    command: sh -c "npm run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./frontend/:/app

  backend:
    image: node:18-alpine
    command: sh -c "npm run start:dev"
    ports:
      - 3001:3000
    working_dir: /app
    volumes:
      - ./backend/:/app

  db:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: dev
      POSTGRES_DB: dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres-data:
